# Generated by Django 2.2.4 on 2020-09-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
