# Generated by Django 2.2.4 on 2020-09-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitem_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(blank=True, default='Ordered', max_length=50, null=True),
        ),
    ]
