# Generated by Django 2.2.4 on 2020-09-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_liked_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
