# Generated by Django 2.2.4 on 2020-09-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_payment_payment_status'),
        ('core', '0002_auto_20200919_0432'),
    ]

    operations = [
    ]
