# Generated by Django 2.2.4 on 2020-09-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_payment_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
