# Generated by Django 2.2.4 on 2020-09-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20200922_0532'),
        ('core', '0006_delete_refund'),
    ]

    operations = [
    ]
