# Generated by Django 2.2.4 on 2020-09-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_wishlist'),
        ('core', '0006_delete_refund'),
    ]

    operations = [
    ]
