# Generated by Django 2.2.4 on 2020-09-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20200922_1911'),
        ('core', '0007_merge_20200923_0933'),
    ]

    operations = [
    ]
